version: '3.9'

services:
  combined-service:
    container_name: combined-service
    build:
      context: .
      dockerfile: Dockerfile  # This will use the combined Dockerfile
    ports:
      - "9000:9000"  # Port for your custom Prism service
    volumes:
      - ./specification:/home/appuser/app/specification  # For hot-reloading the example-chooser (optional)
